'use strict';

// Pure date math for pre-generated recurring sessions (no cron). Kept free of any
// DB or PHI so it is trivially unit-testable and safe to bundle into any Lambda.
//
// All arithmetic is done at UTC midnight (UTC has no DST) so adding whole days or
// months can never drift across a daylight-saving boundary. Dates are the plain
// 'YYYY-MM-DD' strings the sessions table stores — never Date objects with a time.

const ISO_DATE = /^\d{4}-\d{2}-\d{2}$/;

// Supported cadences → interval in days. 'none' is intentionally absent (callers
// treat an unknown/none cadence as a single, non-recurring occurrence).
const CADENCE_DAYS = { weekly: 7, biweekly: 14 };

// Hard cap on sessions generated by a single request (safety backstop; the
// 6-month window keeps weekly runs to ~26 and biweekly to ~13 in practice).
const MAX_OCCURRENCES = 30;

const DAY_MS = 24 * 60 * 60 * 1000;

function parseUTC(s) {
  const p = String(s).split('-');
  return Date.UTC(Number(p[0]), Number(p[1]) - 1, Number(p[2]));
}

function formatUTC(ms) {
  const d = new Date(ms);
  const y = d.getUTCFullYear();
  const m = String(d.getUTCMonth() + 1).padStart(2, '0');
  const day = String(d.getUTCDate()).padStart(2, '0');
  return y + '-' + m + '-' + day;
}

// Add whole calendar months to a 'YYYY-MM-DD' date, returning 'YYYY-MM-DD'.
// Used to compute the "no more than 6 months out" upper bound. Month overflow
// (e.g. Aug 31 + 6mo) rolls forward the same way the platform Date does; that is
// acceptable for a bound check.
function addMonths(startDate, months) {
  const d = new Date(parseUTC(startDate));
  d.setUTCMonth(d.getUTCMonth() + months);
  return formatUTC(d.getTime());
}

// Generate inclusive occurrence dates from startDate through endDate at the given
// cadence. The first element is always startDate. Returns 'YYYY-MM-DD' strings,
// capped at `cap` (default MAX_OCCURRENCES). Behaviour:
//   * cadence 'none' or unknown → just [startDate] (no repeat).
//   * endDate before startDate  → just [startDate].
//   * malformed dates           → just [startDate].
function generateOccurrenceDates(startDate, cadence, endDate, cap) {
  cap = cap || MAX_OCCURRENCES;
  if (!ISO_DATE.test(String(startDate))) return [String(startDate)];

  const step = CADENCE_DAYS[cadence];
  if (!step) return [startDate];
  if (!ISO_DATE.test(String(endDate))) return [startDate];

  const start = parseUTC(startDate);
  const end = parseUTC(endDate);
  if (end < start) return [startDate];

  const out = [];
  for (let cur = start; cur <= end && out.length < cap; cur += step * DAY_MS) {
    out.push(formatUTC(cur));
  }
  return out;
}

module.exports = {
  CADENCE_DAYS,
  MAX_OCCURRENCES,
  addMonths,
  generateOccurrenceDates,
};
